# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created: Mon Sep 16 02:09:51 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(805, 360)
        Dialog.setMinimumSize(QtCore.QSize(805, 360))
        Dialog.setMaximumSize(QtCore.QSize(805, 360))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Índice.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(2.0)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 841, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 780, 303))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.commandLinkButton_12 = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButton_12.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-On-fire.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_12.setIcon(icon1)
        self.commandLinkButton_12.setObjectName(_fromUtf8("commandLinkButton_12"))
        self.gridLayout.addWidget(self.commandLinkButton_12, 5, 1, 1, 1)
        self.btn_histogram = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_histogram.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Slow.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_histogram.setIcon(icon2)
        self.btn_histogram.setObjectName(_fromUtf8("btn_histogram"))
        self.gridLayout.addWidget(self.btn_histogram, 4, 0, 1, 1)
        self.btn_median_filter = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_median_filter.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Grin.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_median_filter.setIcon(icon3)
        self.btn_median_filter.setObjectName(_fromUtf8("btn_median_filter"))
        self.gridLayout.addWidget(self.btn_median_filter, 2, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 7, 0, 1, 1)
        self.btn_watershed = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_watershed.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Evilish.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_watershed.setIcon(icon4)
        self.btn_watershed.setObjectName(_fromUtf8("btn_watershed"))
        self.gridLayout.addWidget(self.btn_watershed, 3, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 7, 1, 1, 1)
        self.commandLinkButton_10 = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButton_10.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Omg.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_10.setIcon(icon5)
        self.commandLinkButton_10.setObjectName(_fromUtf8("commandLinkButton_10"))
        self.gridLayout.addWidget(self.commandLinkButton_10, 4, 1, 1, 1)
        self.btn_mean_filter = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_mean_filter.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Hope-my-fake-smile-works-again.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mean_filter.setIcon(icon6)
        self.btn_mean_filter.setObjectName(_fromUtf8("btn_mean_filter"))
        self.gridLayout.addWidget(self.btn_mean_filter, 1, 0, 1, 1)
        self.btn_threshold = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_threshold.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Angry.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_threshold.setIcon(icon7)
        self.btn_threshold.setObjectName(_fromUtf8("btn_threshold"))
        self.gridLayout.addWidget(self.btn_threshold, 0, 1, 1, 1)
        self.bnt_laplacian = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.bnt_laplacian.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Wut.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bnt_laplacian.setIcon(icon8)
        self.bnt_laplacian.setObjectName(_fromUtf8("bnt_laplacian"))
        self.gridLayout.addWidget(self.bnt_laplacian, 0, 0, 1, 1)
        self.btn_auto_threshold = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_auto_threshold.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Yarr.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_auto_threshold.setIcon(icon9)
        self.btn_auto_threshold.setObjectName(_fromUtf8("btn_auto_threshold"))
        self.gridLayout.addWidget(self.btn_auto_threshold, 1, 1, 1, 1)
        self.btn_gaussian_filter = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_gaussian_filter.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Want.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_gaussian_filter.setIcon(icon10)
        self.btn_gaussian_filter.setObjectName(_fromUtf8("btn_gaussian_filter"))
        self.gridLayout.addWidget(self.btn_gaussian_filter, 3, 0, 1, 1)
        self.btn_otsu = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_otsu.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Yuush.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_otsu.setIcon(icon11)
        self.btn_otsu.setObjectName(_fromUtf8("btn_otsu"))
        self.gridLayout.addWidget(self.btn_otsu, 2, 1, 1, 1)
        self.btn_to_gray_scale = QtGui.QCommandLinkButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Neuropol"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_to_gray_scale.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Bad-Blood-Yolks-Graffiti.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_to_gray_scale.setIcon(icon12)
        self.btn_to_gray_scale.setObjectName(_fromUtf8("btn_to_gray_scale"))
        self.gridLayout.addWidget(self.btn_to_gray_scale, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "UFU/FACOM - BCC/PDI - 2013/1", None))
        self.label.setText(_translate("Dialog", "Choose an action by clicking one of the buttons below:", None))
        self.commandLinkButton_12.setText(_translate("Dialog", "Reduce Size of Image", None))
        self.btn_histogram.setText(_translate("Dialog", "Show Image Histogram", None))
        self.btn_median_filter.setText(_translate("Dialog", "Image Smoothing - Median Filter", None))
        self.pushButton.setText(_translate("Dialog", "About", None))
        self.btn_watershed.setText(_translate("Dialog", "Image Segmentation - Watershed", None))
        self.pushButton_2.setText(_translate("Dialog", "Exit", None))
        self.commandLinkButton_10.setText(_translate("Dialog", "Zoom High Resolution Images", None))
        self.btn_mean_filter.setText(_translate("Dialog", "Image Smoothing - Mean Filter", None))
        self.btn_threshold.setText(_translate("Dialog", "Image Tresholding", None))
        self.bnt_laplacian.setText(_translate("Dialog", "Image Sharpening with Laplacian", None))
        self.btn_auto_threshold.setText(_translate("Dialog", "Image Automatic Thresholding", None))
        self.btn_gaussian_filter.setText(_translate("Dialog", "Image Smoothing - Gaussian Filter", None))
        self.btn_otsu.setText(_translate("Dialog", "Image Segmentation - Otsu", None))
        self.btn_to_gray_scale.setToolTip(_translate("Dialog", "<html><head/><body><p>This action takes an image (preferred a color one) as input and produce a gray-scale version of it. </p></body></html>", None))
        self.btn_to_gray_scale.setText(_translate("Dialog", "Convert Image to Gray Scale", None))

